### ISSUE TITLE
changed UI?

### ISSUE THREAD

**Issue by myrmoteras** [factsmission/synospecies#129]
@retog @nleanba 

the UI seems to have changed and the original timeline with the green, blue, red dots disappeared.
why?

![image](https://github.com/factsmission/synospecies/assets/4609956/5b0044eb-5baa-4e6b-9cba-378ef50ba600)

https://synospecies.plazi.org/#Pipistrellus+pipistrellus

**Comment by nleanba** [comment]
The timeline is still present, you can get to it by scrolling horizontally on the timeline component.

It has been pushed to the side as an unfortunate consequence of displaying all given authorities verbatim (the light gray text).

Synospecies should maybe cut the authorities off here to keep the timeline visible; but this suggest an underlying data problem: this means that the treatments all assign a (subtly) different authority to the taxon concept (many of which wrongly (?) contain the species name again)

**Comment by nleanba** [comment]
Displaying the verbatim authorities was supposed to improve the situation with regards to https://github.com/plazi/names_LOD/issues/154

**Comment by nleanba** [comment]
@retog after quick investigation I found that some of these wrong authorities are no longer in treatments-rdf, but that change seems not to have been picked up by treatment.ld.plazi.org

(compare also the results of this search with the Lindas endpoints, which are more up to date it seems)

can you figure out how to efficiently reimport all data into treatment.ld.plazi.org?

**Comment by retog** [comment]
> @retog after quick investigation I found that some of these wrong authorities are no longer in treatments-rdf, but that change seems not to have been picked up by treatment.ld.plazi.org
> 
> (compare also the results of this search with the Lindas endpoints, which are more up to date it seems)
> 
> can you figure out how to efficiently reimport all data into treatment.ld.plazi.org?

This should be feasible using the SARQL GraphStore protocol, anallogously to how this is done for lindas:

```sh
#!/usr/bin/env bash
set -eo pipefail

set +u
ENDPOINT=${ENDPOINT:=https://stardog-test.cluster.ldbar.ch/lindas}
set -u

cat input/col.nt > upload.nt
cat input/data.nt >> upload.nt


echo "Posting to endpoint: $ENDPOINT"
curl -n \
     --netrc-file config/dot.netrc \
     -X PUT \
     --http1.1 \
     -H Content-Type:application/n-triples \
     -T upload.nt \
     -G $ENDPOINT \
     --data-urlencode graph=https://lindas.admin.ch/foen/plazi

echo "Executing post-insert SPARQL on endpoint: $ENDPOINT/update"
curl -D - -n \
     --netrc-file config/dot.netrc \
     -X POST \
     --http1.1 \
     -H Content-Type:application/sparql-update \
     -T scripts/post-insert.sparql \
     -G $ENDPOINT/update
```

**Comment by nleanba** [comment]
UI is fixed to always have some part of the timeline visible (and all of it reachable by scrolling horizontally), truncating the authority if necessary (full authority is visible below the timeline either way).
