### ISSUE TITLE
"/" symbol meaning

### ISSUE THREAD

**Issue by myrmoteras** [factsmission/synospecies#130]
what does this "/" mean?

![image](https://github.com/factsmission/synospecies/assets/4609956/b481f862-9d81-449c-abb0-61dac42dc961)

https://synospecies.plazi.org/#Pipistrellus+pipistrellus

**Comment by nleanba** [comment]
In different treatments, this taxon-concept has been cited with (slightly) different authorities, the slash ("/") separates the variants given.
