### ISSUE TITLE
same treatment listed twice: Quercus robus

### ISSUE THREAD

**Issue by myrmoteras** [factsmission/synospecies#136]
Do you understand, why in this https://synospecies.plazi.org/#Quercus+robur

the same treatment is mentioned twice?

refers to the same treatment:  https://treatment.plazi.org/id/79FE30612B65BAC136B6D815E21D7BE3

![image](https://github.com/factsmission/synospecies/assets/4609956/6fc8dd9d-2f63-42c4-a3c0-94190ff30896)

**Comment by nleanba** [comment]
This is probably because the treatment both "treatsTaxonName" and "citesTaxonName" the name.

I will update Synospecies to deduplicate these entries.
