### ISSUE TITLE
Turn it into a package

### ISSUE THREAD

**Issue by Daniel-Mietchen** [factsmission/synospecies#33]
to facilitate installation, e.g. by way of npm.

**Comment by retog** [comment]
Hi @Daniel-Mietchen, the widget to select a species with autocompletion is an npm package: https://www.npmjs.com/package/taxomplete. I don't see how the whole would benefit from being a package but maybe individual components like the timeline-widget or the more comprehensive taxon-report. Or do you have more information or an example of a webapp that comes as package?

**Comment by retog** [comment]
Closing for now, as scope of issue unclear.
