### ISSUE TITLE
Images not working anymore

### ISSUE THREAD

**Issue by nleanba** [factsmission/synospecies#41]
@retog

**Comment by retog** [comment]
It looks like the image-splash is getting all he taxa. @nleanba, you made the last commit to imagespash. Not sure ehy you're mentioning me....

**Comment by retog** [comment]
The problem seems to be this line: https://github.com/factsmission/synospecies/blob/c5eafc2bd6fa7fcb1660420d2617ed43d5fd9b78/src/components/ImageSplash.vue#L38, as the taxa don't have a `value` bt a `url` property.

**Comment by retog** [comment]
Taxa used to have `value` but this was changed with https://github.com/factsmission/synospecies/commit/052d2e72996c8099cdf1a4b962f0d3d9d929bf3b#diff-4e09b7c08edcb8d9c7d1b906b2db67a1ed2ff09dd6ddb8618d824e02452873c7R130
