### ISSUE TITLE
Synospecies documentation, paper

### ISSUE THREAD

**Issue by myrmoteras** [factsmission/synospecies#43]
@retog wir sollten eine kurze Beschreibung von Synospecies haben. Möglicherweise wäre es sogar gut, eine wissenschaftliche Arbeit darüber zu schreiben. Hättest du Zeit und Lust dazu?

Es wäre auch gut, bei synospecies.plazi.org  eine kurze Einführung zu haben.

**Comment by retog** [comment]
Ich hab mal ein wiki gestarter und werde dort, verschiedene Aspekte diskutieren, als erster Schritt.

PS: können wir aus Gründen der Koheränz und Inklusivität bei Issues Englisch verwenden?

**Comment by myrmoteras** [comment]
sure - go ahead
