### ISSUE TITLE
synospecies: queries

### ISSUE THREAD

**Issue by myrmoteras** [factsmission/synospecies#44]
@retog hier nochmals die Frage: Kannst Du herausfinden, welche treatments die längsten augment chain hat? Eine solche Liste mit Namen wäre hilfreich, denn dann könnten wir einige heraufiltern, die für die CH wichtig sind.

ein interessantes Bieispiel ist da:
https://synospecies.plazi.org/#Orchis+maculata

und von einem anderen startpunkt 
https://synospecies.plazi.org/#Dactylorhiza+maculata

Kannst Du erklären, warum  die Farben so gewählt sind? Sollte nicht Linnaeus 1753 grün sein?

**Comment by retog** [comment]
@myrmoteras Dasyhelea sternalis Remm 1980 hat 4945 Synonyme. mehr Beispiele hbe ich dir am Donnerstag per Email geschickt.

Ich habe dazu folgende Query verwendet:
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX treat: <http://plazi.org/vocab/treatment#>
SELECT * {
  {
    SELECT DISTINCT ?x (COUNT(DISTINCT ?tc) as ?t ) WHERE {
      {
        SELECT DISTINCT ?x WHERE {
          ?x a <http://filteredpush.org/ontologies/oa/dwcFP#TaxonConcept> .
          ?y treat:deprecates ?x .
        } LIMIT 1000
      }
      ?tc a <http://filteredpush.org/ontologies/oa/dwcFP#TaxonConcept> . 
      ?x ((^treat:deprecates/(treat:augmentsTaxonConcept|treat:definesTaxonConcept))|((^treat:augmentsTaxonConcept|^treat:definesTaxonConcept)/treat:deprecates))* ?tc .
    }
    GROUP BY ?x
  } 
  FILTER (?t > 1) 
}
ORDER BY DESC (?t)
```
Die query funktionier mit Lindas aber nich mit allegro, s. https://github.com/factsmission/synospecies/issues/25. Um das Maximum zu finden, müsste man `LIMIT 1000` enternen, das führt aber bei Lindas zu einem Timeout.

Die Distanz zu kalkulieren, wäre im Prinzip möglich, aber nach den längten Pfäden zu suchen, aber sehr rechenintensiv: https://stackoverflow.com/questions/5198889/calculate-length-of-path-between-nodes
