### ISSUE TITLE
Subspecies are not synonsyms

### ISSUE THREAD

**Issue by retog** [factsmission/synospecies#45]
Looking at https://synospecies.plazi.org/#Sarax+buxtoni I see different subspecies. @nleanba, could you check if this is due because your algorithm expands with everything (rather than just taxa at species rank) that shares the same genus/species?

**Comment by nleanba** [comment]
I don't see any subspecies there

**Comment by retog** [comment]
True for Sarax buxtoni, check Lepus eruropaeus, and most importantly the code

**Comment by nleanba** [comment]
(closed in beta (syg) view)
