### ISSUE TITLE
Add "oh, yeah?"-feature

### ISSUE THREAD

**Issue by retog** [factsmission/synospecies#48]
When synospecies presents a synonym the user should be able to click on a button/link to see the full justification on why synospecies considers this name a synonym of the name the user searched for.

**Comment by nleanba** [comment]
some basic justifications are now implemented

**Comment by nleanba** [comment]
We have two queries tasked with finding synonyms:
1. Using genus & species. Will say "Has queried genus & species" or "Has same genus & species as another synonym"
2. Using an already found taxon concept. Will say "Found to be a synonym for <tc>"

More information is difficult to get as the 2nd query does a lot of stuff all at once.

**Comment by nleanba** [comment]
This feature currently needs enablement via the settings.
Please close the issue if this is satisfactory, @retog .

**Comment by retog** [comment]
Thanks, @nleanba for looking into this so quickly!

I would like to see the full chain of justification with the reference to the respective treatments.

## Example

Query: **Aius bius**

### Justification for the result *Pius qius, Anderson 2020*

- Pius qius, Anderson 2020 is deprecated by Pius rius, Miller 1920  according to the Wong et all (2021), 03A0BE3B6441FFF1FF4FF8CDFE34562A
- Pius rius, Miller 1920 has the same genus & species as Pius rius, Albert 1972
- Pius rius, Albert 1972 deprecates Mius rius, Johnson 1984 according to Agosti D., Peter F. (1998), 0843254398435FFFA4245352134534556
- Mius rius, Johnson 1984 is deprecated by Aius bius, Gadamer 1944 according to Albisser A. (1990), 95434A4656F501ECD34298A534535342
- Aius bius, Gadamer 1944 matches the genus species Aius bius
- Q.E.D.

**Comment by retog** [comment]
In principle, there could be multiple independent justifications on why *Pius quis, Anderson 2020* is a synonym of *Aius bius*, while presenting all justification paths would be nice just having one justification is good enough.

**Comment by nleanba** [comment]
It already shows multiple justifications if a taxon concept is found via multiple queries.

A chain as envisioned by you would necessitate adding more queries and/or splitting up query № 2, which would slow down synospecies quite a bit. If it were to be implemented (which seems tedious), it should definitely be an opt-in feature and using the existing queries only normally.

**Comment by retog** [comment]
I think it should be implemented in a way that does not slow down synospecies. The justification shall only be computed if and when the user requests it for a particular result. The feature is important as it saves us from manually having to do research on complaints about wrong synonyms.

**Comment by retog** [comment]
![image](https://user-images.githubusercontent.com/110756/113975619-11dda780-9840-11eb-91f4-683cca5f0894.png)
This brings us back to #45 but here this is not a synonym because it has the same genus/species but because it explicitly deprecated in http://treatment.plazi.org/id/03AE87BFE84EFFD0A57E0DFAFB6AFAEC.
