### ISSUE TITLE
import of new treatment citations: 

### ISSUE THREAD

**Issue by myrmoteras** [factsmission/synospecies#77]
@retog might it be possible to check the import of this https://treatment.plazi.org/id/D35787D0FF90157AEF40FCE2FD1DFC4F treatment that we changed this morning at 6:10am.

https://synospecies.plazi.org/#Tyrannosaurus+rex

![image](https://user-images.githubusercontent.com/4609956/166138319-23e599a0-e65a-4335-bbfe-29560a669866.png)

the red circled should become a red dot

Would be good to understand that the import works
cheers

**Comment by retog** [comment]
It looks better now:
![image](https://user-images.githubusercontent.com/110756/166885555-f47b657a-3270-4671-b187-f9da208de9d1.png)
The delay in the update was probably related to https://github.com/plazi/treatments-rdf/issues/3
