### ISSUE TITLE
include vernacular names in Synospecies

### ISSUE THREAD

**Issue by myrmoteras** [factsmission/synospecies#89]
there is an interest in the wider public to be able to find names linked to a vernacular names

see also https://github.com/plazi/treatmentBank/issues/65

**Comment by nleanba** [comment]
If vernacular names are given*, they are displayed in Synospecies. Searching for vernacular names is not yet possible in the ui, but the follwing query (use in advanced tab) can be used to get the taxon-names for a given vernacular name:
```SPARQL
PREFIX dwc: <http://rs.tdwg.org/dwc/terms/>
SELECT DISTINCT ?tn WHERE {
  ?tn dwc:vernacularName ?vn .
  FILTER (str(?vn) = "Zwergfledermaus")
}
```
Note that the string has to be an exact match, whether fuzzy searching is possible (and how to do it) depends on the endpoint.

*note: currently, synospecies only knows of the (few) vernacular names listed in https://github.com/plazi/treatments-rdf/blob/main/vernacular/bats.ttl. I will create an issue in gg2rdf to get vernacular names from the xml.

**Comment by nleanba** [comment]
Open todo: Synospecies currently only displays vernacular Names with an associated language, it shiuld also display those without.

**Comment by klausriede** [comment]
Notabene: vernacular names are often more stable than scientific names...example: birds
