### ISSUE TITLE
Order of authors

### ISSUE THREAD

**Issue by retog** [factsmission/synospecies#97]
The order of treatment authors in the rendering on https://synospecies.plazi.org/#Tyrannosaurus+rex does not reflect the order in https://github.com/plazi/treatments-rdf/blob/ed436d1e725e48738b288c051a96d0f38c89f124/data/03/E8/48/03E8486CFFE30E52FFBE5400FBC3FE74.ttl#L172. Why?

**Comment by nleanba** [comment]
these are separate triples and thus unordered

**Comment by nleanba** [comment]
Duplicate of https://github.com/plazi/names_LOD/issues/155

This is not an issue in synospecies directly, but in the xml/rdf conversion process.
