### ISSUE TITLE
Update Material Citation display

### ISSUE THREAD

**Issue by nleanba** [factsmission/synospecies#99]
(See https://github.com/plazi/names_LOD/issues/133):
- [x] Links to GBIF
- [x] Reformat additional info as to include GBIF-IDs and httpUri
- [x] (This potentially requires changes to the SPARQL-Query)

(See https://github.com/plazi/treatments-xml/issues/11):
- [x] Proper links to the citation (only for matCits with UUID in RDF)

UX:
- [x] Mark / Emphasize Holotype
- [x] Change clunky hover-mechanism to something easier and more discoverable
- [ ] For Treatments with a lot of matCits, it's very hard to read (confusing and cluttered) → Maybe sorting and grouping by Collection; and/or better separation between the entries

**Comment by nleanba** [comment]
![Screenshot from 2023-04-03 19-28-20](https://user-images.githubusercontent.com/25827850/229587230-33a92f3e-23b7-417e-a333-08e6761c2706.png)

Current UI for reference

**Comment by nleanba** [comment]
![image](https://user-images.githubusercontent.com/25827850/229595241-71eb7a24-3c1e-4fb2-8fb6-77747830daad.jpeg)

**Comment by retog** [comment]
Just something minor: Instead of "Cited Materials (3)" say "3 Cited Materials", or even more understandable for my lay ears "3 specimens referenced".

**Comment by nleanba** [comment]
How's this? (currently live as such)
![image](https://user-images.githubusercontent.com/25827850/230656164-adf08456-b747-4936-8b9f-451e7fc0eabc.png)

**Comment by nleanba** [comment]
@retog @myrmoteras opinions? 

![image](https://user-images.githubusercontent.com/25827850/231181628-2606d939-60c4-4b6d-a812-4d46fc88f441.png)

> note: clicking anywhere on the label “X specimens referenced” opens the popup. Making the whole text look like a button (with background etc. looked way too visually heavy and distracting)

Unless either of you has some remaining issues or suggestions for this display, I consider this done and will close this issue.

**Comment by myrmoteras** [comment]
I would use "material citation" since this is the term we coined for a reference of one or multiple specimens used in an analysis, which is used this way in TDWG DWC https://dwc.tdwg.org/terms/#materialcitation and also in the GBIF data model https://www.gbif.org/occurrence/search?basis_of_record=MATERIAL_CITATION&occurrence_status=present basisOfRecord

**Comment by myrmoteras** [comment]
should we change "GBIF occurrence ID" to "GBIF material citation"? 

if so we could also change "GBIF specimen ID" to "GBIF preserved specimen" 
![image](https://user-images.githubusercontent.com/4609956/232212636-5e3380e5-bea6-414f-a2cf-663813c97250.png)

**Comment by myrmoteras** [comment]
@tcatapano terminology to be discussed?!
